name: new_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  firebase_storage: ^11.2.2
  shared_preferences: ^2.1.1
  fluttertoast: ^8.2.2
  image_picker: ^0.8.7+5
  lottie: ^2.3.2
  uuid: ^3.0.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
